### PR TITLE
Add link to (free) API

### PR DESCRIPTION
**Pull request by mherrmann**

### CODE REVIEW

**Comment by mherrmann** [comment]
Hi Rachel, is there any chance you've had to look at my Pull Request yet?

**Comment by rachelandrew** [comment]
I'm probably taking this resource offline as it's pretty old info now.

**Comment by mherrmann** [comment]
I see. Until you do, you could keep it a little more up-to-date by merging the PR?

**Comment by rachelandrew** [comment]
I'm no longer updating this, having one recent link makes it look like it is being updated.

**Pull request closed without merging**
